-- 코드를 입력하세요
-- 조회수가 가장 높은 게시물의
-- 첨부파일 경로
-- 파일ID, 파일 이름, 파일 확장자 (USED_GOODS_FILE) 로 구성
-- FILE ID 기준 내림차순

SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_FILE AS B ON A.BOARD_ID = B.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC
