-- 코드를 입력하세요
-- [TRAIL & ERROR 1]
-- [WRONG] SELECT절에서 MAX(PRICE)를 하면 다른 변수들은 그대로고 가격만 가장 높은 데이터로 추출됨
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
ORDER BY PRICE DESC

-- [SOLVE]
-- WHERE절 이용
SELECT  *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

