-- 코드를 입력하세요
-- 7일 이상 ID, 평균 대여 기간 (소수점 둘째 자리에서 반올림)

SELECT CAR_ID, ROUND(AVG(ABS(DATEDIFF(START_DATE, END_DATE))+1),1) AS AVERGAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERGAGE_DURATION >= 7
ORDER BY AVERGAGE_DURATION DESC, CAR_ID DESC