-- 코드를 입력하세요
-- 7일 이상 ID, 평균 대여 기간 (소수점 둘째 자리에서 반올림)

-- [TRIAL & ERROR 1]
-- [ERROR]
SELECT CAR_ID, ROUND(AVG(ABS(DATEDIFF(START_DATE, END_DATE))),1) AS AVERGAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY HISTORY_ID
WHERE ROUND(AVG(ABS(DATEDIFF(START_DATE, END_DATE))),1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC


-- [SOLUTION]
-- 날짜 차이 계산할 때, +1 해줘야 함
-- WHERE 말고 HAVING을 써서 조건 부여해야 함 (HAVING은 무조건 GROUP_BY 뒤에 오는 조건절, WHERE은 항상 FROM 뒤에 오는 조건)
SELECT CAR_ID, ROUND(AVG(ABS(DATEDIFF(START_DATE, END_DATE))+1),1) AS AVERGAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERGAGE_DURATION >= 7
ORDER BY AVERGAGE_DURATION DESC, CAR_ID DESC
