-- 생산일자가 2022년 5월인 식품들
-- 식품ID, 식품 이름, 총매출(수량*가격)
-- 총매출 기준 내림차순, 식품ID 기준 오름차순

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE("2022-05-%%")
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC