-- 코드를 입력하세요
-- 상품코드 별 매출액 GROUP BY 상품코드, SUM (SALES)

-- [TRIAL & ERROR 1]
-- [WRONG]  : SALES_AMOUNT를 미리 묶고 PRICE랑 곱해야할 거 같음 (아니었음)

SELECT A.PRODUCT_CODE, A.PRICE*B.SALES_AMOUNT AS SALES
FROM PRODUCT A
INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE HAVING SUM(SALES)
ORDER BY SALES DESC, PRODUCT_CODE ASC


-- [SOLVE] : GROUP BY 쓸 때, SELECT 절에서 GROUP BY할 컬럼과 집계함수를 적어줘야 함
-- [example] : SELECT column, 집계함수(column); FROM table; GROUP BY column;

SELECT A.PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) AS SALES
FROM PRODUCT A
INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
