-- 코드를 입력하세요
-- 상품코드 별 매출액 GROUP BY 상품코드, SUM (SALES)

SELECT A.PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) AS SALES
-- A.PRICE*B.SALES_AMOUNT AS SALES
FROM PRODUCT A
INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
