-- 코드를 입력하세요
-- 2022.4.13 취소되지 않은 흉부외과(CS) 진료 예약 내역(APPOINTMENT -> APNT_CNCL_YN = N)
-- B.진료예약번호, A.환자이름, A.환자번호, B.진료과코드, C.의사이름, B.진료예약일시
-- 진료예약일시 오름차순

SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT AS A
JOIN APPOINTMENT AS B ON A.PT_NO = B.PT_NO
JOIN DOCTOR AS C ON B.MDDR_ID = C.DR_ID
-- (SELECT C.DR_NAME FROM APPOINTMENT AS B JOIN DOCTOR AS C ON B.DR_ID = C.DR_ID)
WHERE B.MCDP_CD LIKE 'CS' AND B.APNT_CNCL_YN LIKE 'N' 
AND B.APNT_YMD LIKE '%2022-04-13%'
ORDER BY B.APNT_YMD ASC


