-- 코드를 입력하세요
-- 경제 카테고리에 속해야 함
-- BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE 리스트 출력
-- 출판일 기준 오름차순

SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY = "경제"
ORDER BY BOOK.PUBLISHED_DATE ASC