-- 코드를 입력하세요
-- SEN [SOLVE]
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE LIKE "세단"
AND START_DATE LIKE "%%-10-%%"
ORDER BY CAR_ID DESC

-- [SOLUTION]
-- CAR_ID 중복이 없어야 한다 - DISTINCT
-- 대여 기록이 있어야 한다 - ON A.CAR_ID = B.CAR_ID
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE)=10
ORDER BY CAR_ID DESC
