-- 코드를 입력하세요
-- [TRIAL & ERROR 1]
-- [WRONG]
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE "%EL%"
ORDER BY NAME

-- [TRIAL & ERROR 2]
-- [SOLVE] : 강아지들 중에 이름이 "EL" 들어가 있는 애들 뽑았어야 함.
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE LIKE "DOG"
AND NAME LIKE "%EL%"
ORDER BY NAME
